services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "9090:9090"
    networks:
      - musicman

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - musicman

networks:
  musicman:
    driver: bridge
